### ISSUE TITLE
Error in starting up kolo on OSX, with Postgresql in Docker Image

### ISSUE THREAD

**Issue by bbuehlmann** [kolofordjango/kolo#30]
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2022-09-23 17:26:29,544 kolo INFO Kolo config file "/Users/****/Django/eliza.app/.kolo/config.toml" not found. Using default configuration.
2022-09-23 17:26:39,829 kolo DEBUG Unexpected exception in default_include_frames: <kolo.filters.sql.SQLQueryFilter object at 0x10e8b5d60>
Traceback (most recent call last):
  File "/Users/****/Django/eliza.app/.venv/lib/python3.8/site-packages/kolo/profiler.py", line 171, in __call__
    frame_data = frame_filter.process(
  File "/Users/****/Django/eliza.app/.venv/lib/python3.8/site-packages/kolo/filters/sql.py", line 115, in process
    data = serialize_query_data(arg)
  File "/Users/****/Django/eliza.app/.venv/lib/python3.8/site-packages/kolo/serialize.py", line 94, in serialize_query_data
    for row in rows:

**Comment by wilhelmklopp** [comment]
👋 Hey @bbuehlmann – thanks for opening this issue and sorry for the slow reply here.

I believe we fixed this issue in version 2.2.0 of Kolo 🙌 

Would you be able to try again on the latest version of the kolo python package (2.3.0) and let us know if you're still seeing any issues?

Thanks!

**Comment by wilhelmklopp** [comment]
Will go ahead and close this, but feel free to open another issue if you're still seeing problems :)
