### ISSUE TITLE
KeyError: 'cursor'

### ISSUE THREAD

**Issue by yml** [kolofordjango/kolo#40]
```python
Unexpected exception in default_include_frames: <kolo.filters.sql.SQLQueryFilter object at 0x7f9677550250>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/kolo/profiler.py", line 173, in __call__
    frame_data = frame_filter.process(
  File "/usr/local/lib/python3.10/site-packages/kolo/filters/sql.py", line 92, in process
    cursor = frame.f_locals["cursor"]
KeyError: 'cursor'
```

**Comment by wilhelmklopp** [comment]
@LilyFoote maybe we can fall back to not capturing any query data when the cursor local doesn't exist?
