### ISSUE TITLE
Recursion error when generating tests

### ISSUE THREAD

**Issue by dvielen** [kolofordjango/kolo#74]
All other Kolo functionalities work as expected. However when generating a test I get the following error:

```
(.venv)  ✘ user_name@mbp-099882  ~/IdeaProjects/signer/backend   master ±✚  kolo generate-test trc_01HDDQKAPTE6Z4FNC7W5K91810 --settings=settings.dev
Traceback (most recent call last):
  File "/Users/user_name/IdeaProjects/signer/.venv/bin/kolo", line 8, in <module>
    sys.exit(cli())
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/__main__.py", line 428, in generate_test
    test_code = generate_from_trace_id(
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/__init__.py", line 82, in generate_from_trace_id
    run_processors(processors, context)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/processors.py", line 172, in run_processors
    processor_output = processor(context)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/processors.py", line 59, in process_sql_queries
    sql_fixtures, imports, asserts = parse_sql_queries(sql_queries, schema_data)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 815, in parse_sql_queries
    sql_fixtures = sorted(deduplicated, key=make_table_sort_key(schema_data))
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 680, in sort_key
    return (table_depth(create.table), create.table, create.values)
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
```
...
```
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in table_depth
    return max(table_depth(related) for related in related_tables) + 1
  File "/Users/user_name/IdeaProjects/signer/.venv/lib/python3.8/site-packages/kolo/generate_tests/queries.py", line 676, in <genexpr>
    return max(table_depth(related) for related in related_tables) + 1
RecursionError: maximum recursion depth exceeded while calling a Python object```

**Comment by dvielen** [comment]
Seems like the issue is because we have a self reference in on of our models. I managed to get it to work by replacing line 677 in kolo/generate_tests/queries.py 
from
```
        return max(table_depth(related) for related in related_tables) + 1
```
to

```
        return max(table_depth(related) for related in related_tables if related != table) + 1
```

**Comment by LilyFoote** [comment]
@dvielen [Fixed in 2.16.2](https://docs.kolo.app/en/latest/python-changelog.html#id1).
