### ISSUE TITLE
Error in "Test" tab

### ISSUE THREAD

**Issue by ghost** [kolofordjango/kolo#88]
Hello there!

I´m trying kolo for the first time(it looks really great), following the Quickstart, but I have been receiving an error in the test tab(Trace works fine), that make it break completely.

`TypeError: this.input.chunk is not a function
    at d.getChunk (http://127.0.0.1:8000/_kolo/static/main.js:2:998685)
    at d.readNext (http://127.0.0.1:8000/_kolo/static/main.js:2:998882)
    at new d (http://127.0.0.1:8000/_kolo/static/main.js:2:997254)
    at new y (http://127.0.0.1:8000/_kolo/static/main.js:2:1005451)
    at _.createParse (http://127.0.0.1:8000/_kolo/static/main.js:2:1012131)
    at _.startParse (http://127.0.0.1:8000/_kolo/static/main.js:2:878590)
    at _.parse (http://127.0.0.1:8000/_kolo/static/main.js:2:878637)
    at http://127.0.0.1:8000/_kolo/static/main.js:2:2270797
    at rl (http://127.0.0.1:8000/_kolo/static/main.js:2:121097)
    at yc (http://127.0.0.1:8000/_kolo/static/main.js:2:141042)`
    
    
![kolo_error](https://github.com/user-attachments/assets/e15f07a4-880e-4995-bfac-2712b6dd388f)

Am I doing something wrong? Is it possible that there is an error with my setup? Or is this a known error?

Thank you.

**Comment by wilhelmklopp** [comment]
@Marcos-Mdona thanks for the report sorry for the very slow reply here, not sure how i missed this!

I believe we fixed this bug in v2.33.3 of Kolo, so if you upgrade to the latest version (v2.33.6), it should all work 😁 

Please let me know if you're still having issues
